name: Docker Image build

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_call:
    inputs:
      docker_registry:
        default: docker.ethquokkaops.io
        type: string
      docker_registry_project:
        default: ethquokkaops
        type: string
      use_artifact:
        type: boolean
        default: false
      artifact_path:
        type: string
      artifact_name:
        type: string
      build_args:
        type: string
        description: "JSON string of build arguments to pass to docker build"
        required: false
      dockerfile:
        type: string
        default: Dockerfile
    secrets:
      docker_registry_user:
        required: true
      docker_registry_password:
        required: true

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Download artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}
        if: ${{ inputs.use_artifact }}

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4
        with:
          registry: ${{ inputs.docker_registry }}
          username: ${{ secrets.docker_registry_user }}
          password: ${{ secrets.docker_registry_password }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7
        with:
          images: ${{ inputs.docker_registry }}/${{ inputs.docker_registry_project }}/${{ github.repository }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16
        with:
          file: ${{ inputs.dockerfile }}
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ${{ inputs.build_args }}

