name: Deploy via ArgoCD

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_call:
    inputs:
      team:
        type: string
      project:
        type: string
    secrets:
      cypher_client_id:
        required: true
      cypher_client_secret:
        required: true

jobs:
  deploy-to-argocd:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: Infisical/secrets-action@08d433afae6a851f9081d0563a01a55fdf96568b # v1.0.11
        with:
          client-id: ${{ secrets.cypher_client_id }} # Update this to your own Github references
          client-secret: ${{ secrets.cypher_client_secret }} # Update this to your own Github references
          env-slug: "prod"
          secret-path: "/deploy"
          project-slug: "gh-actions-deploy-65-js"
          domain: "https://cypher.ethquokkaops.io"
      
      - name: Checkout the iac repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ethdevops/internal-stack-iac
          ref: main
          token: ${{ env.GH_IAC_TOKEN }} # Use the GitHub token for authentication
          path: internal-stack-iac

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get current tag
        id: get_tag
        run: echo "TAG=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

      - name: Update values.version.yaml
        run: |
          echo -e "simple-website:\n  imageVersion: $TAG" > internal-stack-iac/${{ inputs.team }}/${{ inputs.project }}/argocd/values.version.yaml
      

      - name: Commit and push changes
        run: |
          cd internal-stack-iac
          git add ${{ inputs.team }}/${{ inputs.project }}/argocd/values.version.yaml
          git commit -m "Deploy ${{ inputs.team }}/${{ inputs.project }} to $TAG"
          git push origin main
